name: crisis_link
description: BayMax - AI-assisted emergency operations and public safety application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8

  # Maps & Location
  google_maps_flutter: ^2.12.1
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  flutter_launcher_icons: ^0.14.4

  # State Management
  flutter_riverpod: ^2.6.1

  # Navigation
  go_router: ^15.1.2

  # UI
  fl_chart: ^0.70.2
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  flutter_animate: ^4.5.2
  lottie: ^3.3.1

  # Image
  image_picker: ^1.1.2

  # Utils
  intl: ^0.20.2
  uuid: ^4.5.1
  url_launcher: ^6.3.1

  # Icons
  cupertino_icons: ^1.0.8
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/theme/applogo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "lib/theme/applogo.png"